<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-MATN0N1" failures="2" tests="2" name="Test1" time="0.008" errors="0" timestamp="2022-02-20T01:50:07 IST">
  <testcase classname="TestPackage.ValidationClass" name="MakeActiveToDo2Completed" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at TestPackage.ValidationClass.MakeActiveToDo2Completed(ValidationClass.java:52)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- MakeActiveToDo2Completed -->
  <testcase classname="TestPackage.ValidationClass" name="DeleteTodos1" time="0.005">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at TestPackage.ValidationClass.DeleteTodos1(ValidationClass.java:35)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- DeleteTodos1 -->
</testsuite> <!-- Test1 -->
